import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex justify-center">
          <div className="flex flex-row items-center place-content-evenly gap-4 outline w-full h-16 p-4">
            <Link href="/">
              <div>Home</div>
            </Link>
            <Link href="/">
              <div>Feed</div>
            </Link>
            <Link href="/">
              <div>Home</div>
            </Link>
          </div>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
